export default ([
  {
    image: 'https://m.media-amazon.com/images/I/71aS4BH+58L._SX522_.jpg',
    name: '30',
    artist: 'Adele',
    price: 33.99,
    id: 0,
    newArrival: false,
    backgroundColor: 'lightblue',
  },
  {
    image: 'https://m.media-amazon.com/images/I/71k1MDO27HL._AC_UY436_QL65_.jpg',
    name: 'Dreamland',
    artist: 'Glass Animals',
    price: 28.99,
    id: 1,
    newArrival: false,
    backgroundColor: 'rgb(255, 199, 248)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/91ZZsD5t+zL._SX522_.jpg',
    name: 'The College Dropout',
    artist: 'Kanye',
    price: 24.99,
    id: 2,
    newArrival: false,
    backgroundColor: 'rgb(255, 216, 158)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81FEIwvwXrL._SX522_.jpg',
    name: 'Call Me if You Are Lost',
    artist: 'Tyler the Creator',
    price: 27.99,
    id: 3,
    newArrival: false,
    backgroundColor: 'lightblue',
  },
  {
    image: 'https://m.media-amazon.com/images/I/61Ia07wdZQL._SX522_.jpg',
    name: 'Random Access Memories',
    artist: 'Daft Punk',
    price: 29.99,
    id: 4,
    newArrival: false,
    backgroundColor: 'rgb(230 230 230)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81OfXQOiR9L._AC_UY436_QL65_.jpg',
    name: 'Be the Cowboy',
    artist: 'Mitski',
    price: 24.99,
    id: 5,
    newArrival: false,
    backgroundColor: 'rgb(251, 216, 216)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/416uFuXmEOL._AC_UY436_QL65_.jpg',
    name: 'Madvillainy',
    artist: 'Madvillain',
    price: 22.99,
    id: 6,
    newArrival: false,
    backgroundColor: 'rgb(228, 228, 228)',
  },
  {
    image: 'https://www.sanborns.com.mx/imagenes-sanborns-ii/1200/194399456828.jpg',
    name: 'Planet Her',
    artist: 'Doja Cat',
    price: 26.99,
    id: 7,
    newArrival: true,
    backgroundColor: 'rgb(156, 110, 221)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/717kcsRRb7L._SX522_.jpg',
    name: 'Awaken, My Love!',
    artist: 'Childish Gambino',
    price: 19.99,
    id: 8,
    newArrival: false,
    backgroundColor: 'lightblue',
  },
  {
    image: 'https://m.media-amazon.com/images/I/614e7Q42t8L._AC_UY436_QL65_.jpg',
    name: 'Pet Sounds',
    artist: 'Beach Boys',
    price: 24.99,
    id: 9,
    newArrival: false,
    backgroundColor: 'rgb(172, 235, 172)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/A1Uv+OPV22S._AC_UY436_QL65_.jpg',
    name: 'Illmatic',
    artist: 'Nas',
    price: 24.99,
    id: 10,
    newArrival: false,
    backgroundColor: 'rgb(247, 211, 160)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/71VpqI19tpL._AC_UY436_QL65_.jpg',
    name: 'Ride the Lightning',
    artist: 'Metallica',
    price: 20.99,
    id: 11,
    newArrival: false,
    backgroundColor: 'lightblue',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81vaOIWJkcL._AC_UY436_QL65_.jpg',
    name: 'In the Aeroplane Over the Sea',
    artist: 'Neutral Milk Hotel',
    price: 14.99,
    id: 12,
    newArrival: false,
    backgroundColor: 'rgb(255, 243, 174)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/61ur3nQ+-mL._SX522_.jpg',
    name: "Harry's House",
    artist: 'Harry Styles',
    price: 31.99,
    id: 13,
    newArrival: true,
    backgroundColor: 'rgb(251, 213, 161)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81CP1j-zprL._AC_UY436_QL65_.jpg',
    name: 'Kinda Blue',
    artist: 'Miles Davis',
    price: 19.99,
    id: 14,
    newArrival: false,
    backgroundColor: 'lightblue',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81LqOaYCRjL._AC_UY436_QL65_.jpg',
    name: 'Isolation',
    artist: 'Kali Uchis',
    price: 29.99,
    id: 15,
    newArrival: false,
    backgroundColor: 'rgb(90, 110, 244)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/61lZf+MnEIL._AC_UY436_QL65_.jpg',
    name: 'Currents',
    artist: 'Tame Impala',
    price: 19.99,
    id: 16,
    newArrival: false,
    backgroundColor: 'rgb(175, 82, 246)',
  },
  {
    image: 'https://pure-music.co.uk/wp-content/uploads/2018/12/dark-side-of-the-moon-album-cover.jpg',
    name: 'Dark Side of the Moon',
    artist: 'Pink Floyd',
    price: 29.99,
    id: 17,
    newArrival: false,
    backgroundColor: 'lightcoral',
  },
  {
    image: 'https://images-na.ssl-images-amazon.com/images/I/51BLpSt6DqL._SX300_SY300_QL70_ML2_.jpg',
    name: 'Take Care',
    artist: 'Drake',
    price: 24.99,
    id: 18,
    newArrival: false,
    backgroundColor: 'rgb(255, 216, 158)',
  },
  {
    image: 'https://m.media-amazon.com/images/I/81T8HWCy17L._AC_UY436_QL65_.jpg',
    name: 'Saturday Night Fever',
    artist: 'Bee Gees',
    price: 22.99,
    id: 19,
    newArrival: false,
    backgroundColor: 'gold',
  },
  {
    image: 'https://m.media-amazon.com/images/I/71PD1ZbRBAL._AC_UY436_QL65_.jpg',
    name: 'Mordechai',
    artist: 'Khruangbin',
    price: 20.99,
    id: 20,
    newArrival: false,
    backgroundColor: 'rgb(255, 228, 158)',
  },
  {
    image: 'https://media.pitchfork.com/photos/61d5fa911b710fb5ce48ed9f/1:1/w_600/The-Weeknd-Dawn-FM.jpg',
    name: 'Dawn FM',
    artist: 'The Weeknd',
    price: 29.99,
    id: 21,
    newArrival: true,
    backgroundColor: 'rgb(158, 219, 255)',
  },
  {
    image: 'https://i.discogs.com/vtNfu2TuoRjwT7IQJg0ZFAODmYucZPhKeRE-Xxz_evc/rs:fit/g:sm/q:90/h:535/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIyNTU2/NTE5LTE2NDc2MjIx/MDAtODEwNi5qcGVn.jpeg',
    name: 'Crash',
    artist: 'Charli XCX',
    price: 25.99,
    id: 22,
    newArrival: true,
    backgroundColor: 'rgb(158, 219, 255)',
  },

  {
    image: 'https://media.pitchfork.com/photos/627c1023d3c744a67a846260/master/pass/Kendrick-Lamar-Mr-Morale-And-The-Big-Steppers.jpghttps://media.pitchfork.com/photos/627c1023d3c744a67a846260/master/pass/Kendrick-Lamar-Mr-Morale-And-The-Big-Steppers.jpg',
    name: 'Mr.Morale & the Big Steppers',
    artist: 'Kendrick Lamar',
    price: 29.99,
    id: 23,
    newArrival: true,
    backgroundColor: 'rgb(255, 216, 158)',
  },
  {
    image: 'https://media.pitchfork.com/photos/61d740b79a8903a73574e2a5/1:1/w_600/FKA-twigs-Caprisongs.jpg',
    name: 'Caprisongs',
    artist: 'FKA Twigs',
    price: 29.99,
    id: 24,
    newArrival: true,
    backgroundColor: 'rgb(113, 174, 242)',
  },
  {
    image: 'https://i.discogs.com/4bJFf12z0BjQ1BwXlBavMoSDDrDrA1eQiv_CRXUg-nM/rs:fit/g:sm/q:90/h:600/w:600/czM6Ly9kaXNjb2dz/LWRhdGFiYXNlLWlt/YWdlcy9SLTIzNjAy/NTExLTE2NTU0NjE2/NDctNzEwNS5qcGVn.jpeg',
    name: 'Honestly, Nevermind',
    artist: 'Drake',
    price: 29.99,
    id: 25,
    newArrival: true,
    backgroundColor: 'rgb(158, 166, 244)',
  },

]);

// {
//   image:
//   name:
//   artist:
//   price:
//   id:
// },
